import {
  AirlineMileage,
  Shopping,
  SimplePayment,
  PointCashback,
  ConvenienceStore,
  LargeMart,
  CafeBakery,
  PaymentBenefits,
  DiningOut,
  Medical,
  Pets,
  Beauty,
  PublicTransport,
  Fuel,
  HiPass,
  Education,
  Childcare,
  Culture,
  Leisure,
  Movies,
  Telecom,
  ManagementFees,
  PriorityPass,
  Premium,
  Auto,
  Finance,
  DebitCardCompatible,
  Voucher,
  AlwaysDiscount,
  Rental,
  CompactCarFuelRefund,
  AnnualFeeSupport,
  NationalHappinessCard,
  GreenCard
} from "@/icons/categoryIcons";

export const CategoryIcons = {
  "항공마일리지": <AirlineMileage />,
  "쇼핑": <Shopping />,
  "간편결제": <SimplePayment />,
  "포인트/캐시백": <PointCashback />,
  "편의점": <ConvenienceStore />,
  "대형마트": <LargeMart />,
  "카페/베이커리": <CafeBakery />,
  "납부 혜택": <PaymentBenefits />,
  "외식": <DiningOut />,
  "의료": <Medical />,
  "반려동물": <Pets />,
  "뷰티": <Beauty />,
  "대중교통": <PublicTransport />,
  "주유": <Fuel />,
  "하이패스": <HiPass />,
  "교육": <Education />,
  "육아": <Childcare />,
  "문화": <Culture />,
  "레저": <Leisure />,
  "영화": <Movies />,
  "통신": <Telecom />,
  "관리비": <ManagementFees />,
  "Priority Pass": <PriorityPass />,
  "프리미엄": <Premium />,
  "오토": <Auto />,
  "금융": <Finance />,
  "체크카드겸용": <DebitCardCompatible />,
  "바우처": <Voucher />,
  "언제나할인": <AlwaysDiscount />,
  "렌탈": <Rental />,
  "경차유류환급": <CompactCarFuelRefund />,
  "연회비지원": <AnnualFeeSupport />,
  "국민행복카드": <NationalHappinessCard />,
  "그린카드": <GreenCard />
};
